### ISSUE TITLE
Icons are not available in store settings

### ISSUE THREAD

**Issue by Eduard-CA** [activemerchant/payment_icons#578] opened 2022-02-26 13:51 UTC
Have problem with payment icons in store settings. Icons from PR: https://github.com/activemerchant/payment_icons/pull/533

Payment icons available in the lists of payment methods (payment application settings). 
![image](https://user-images.githubusercontent.com/81959588/155845276-20ce342c-94f2-4b39-8248-e1e67cc8cb92.png)

This is the published version of the payment extension.
But merchant can`t to change payment methods in the store settings (except satisFi)
![image](https://user-images.githubusercontent.com/81959588/155845410-dfcc01e3-e797-423f-9610-42e19ccb6f8a.png)

Extends: Acima Leasing, Synchrony Pay, SatisFi, Checkout Financing, Echelon Financing
Actual: SatisFi

Let me know if you need more information. 
Thanks!

**Comment by larouxn** [comment] 2022-03-04 08:21
👋 @Eduard-CA, thanks for bringing this to our attention. To clarify, the icons are available in the partners dashboard (app/gateway settings) but _not_ in the admin/shop payment settings. Is this correct?

**Comment by yuriykipnis** [comment] 2022-03-08 05:42
@larouxn correct.
The images are available and configured in gateway settings. 
We expect the images to appear in the app setting in a store admin. The problem is that only one image appears, out of 5 that were defined in the gateway.
We also found that the issue is somehow related to these 4 images in particular. On the other side all 5 images we uploaded have identical format.

**Comment by larouxn** [comment] 2022-03-11 03:45
👋 Hey @yuriykipnis, we've shipped a potential fix for this issue. Can you take a look and let us know? Feel free to close the issue if it's resolved.

**Comment by yuriykipnis** [comment] 2022-03-13 16:35
Thanks @larouxn! 
The issue is fixed.

**Closed** 2022-03-14 07:41 UTC
